package com.free.entity.DO;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.desc
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.desc
     *
     * @return the value of permission.desc
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.desc
     *
     * @param desc the value for permission.desc
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}