package com.free.shiro.dao;

import java.util.List;

import com.free.shiro.entity.DO.Permission;
import com.free.shiro.entity.DO.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Tue May 01 12:54:10 CST 2018
     */
    List<RolePermission> selectAll();

	List<Permission> selectByRoleId(String id);
}